### ISSUE TITLE
Can't get the stocks data

### ISSUE THREAD

**Issue by Lingfeng713** [ValueCell-ai/valuecell#196]
Hello, Thank you for your answer.
when opening the homepage, it displays the following error and I can't get the stocks data:

1.Historical price data not available for'SSE:000001'
2.Historical price data not available for 'HKEX:HSI’
3.Price data not available for 'NASDAQ:IXIC’

How can I resolve this issue?

**Comment by bomb-coin** [comment]
me too 

<img width="603" height="252" alt="Image" src="https://github.com/user-attachments/assets/3092b9ef-7177-47df-9a62-2c44685e0efc" />

**Comment by Lingfeng713** [comment]
> me too
> 
> <img alt="Image" width="603" height="252" src="https://private-user-images.githubusercontent.com/87158576/506079772-3092b9ef-7177-47df-9a62-2c44685e0efc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2Mjg1ODksIm5iZiI6MTc2MTYyODI4OSwicGF0aCI6Ii84NzE1ODU3Ni81MDYwNzk3NzItMzA5MmI5ZWYtNzE3Ny00N2RmLTlhNjItMmM0NDY4NWUwZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA1MTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTEwZWNlNGUwMWJjMzVmOGI4YzQyZGI4MzBkZWU1OGNhOGEwYzU3OThkNmU4Y2E5ODY1ODk5ZWNkNGU3NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t2GuxHXrhOtkOYxIkmO5mwuAhsQ4TQxZeGOwbilcQTg">

if you solve it , please share with me ,thx

**Comment by vcfgv** [comment]
Hi, thank you for bringing this up. It has been addressed in #183 . 
> Use git pull to update the code, then delete the valuecell.db file in the project directory and restart the application.

**Comment by vcfgv** [comment]
@Lingfeng713 Noticed that you are still facing this issue, as replied in #238 . This issue is reopened and could you please provide more details for us to better investigate?

**Comment by Lingfeng713** [comment]
> [@Lingfeng713]@(https://github.com/Lingfeng713)  Noticed that you are still facing this issue, as replied in [#238](https://github.com/ValueCell-ai/valuecell/issues/238) . This issue is reopened and could you please provide more details for us to better investigate?

@vcfgvThank you for your support. As per your previous guidance, I have git the latest code and also deleted valuecell.db before running the program again. Currently, I am able to use the Agent normally, but I still cannot retrieve stock data. I also tried using the Xueqiu token(xq_a_token), but it didn't work well . What other information do you think I need to provide?

<img width="482" height="419" alt="Image" src="https://github.com/user-attachments/assets/d26e2d49-7c40-45df-96d4-b6913ee4ee98" />
<img width="1031" height="569" alt="Image" src="https://github.com/user-attachments/assets/d66e7a12-574e-497a-b264-552ddfbac9d7" />
<img width="826" height="96" alt="Image" src="https://github.com/user-attachments/assets/f7c26346-9389-4ab0-82e8-303fa344f4aa" />
<img width="1080" height="588" alt="Image" src="https://github.com/user-attachments/assets/1e1a3e9e-52b0-4822-b083-53c2d8f7e0ba" />

**Comment by harrisonyao** [comment]
@vcfgv  I just noticed you close the ticket #238 , but I have to say the issues in that ticket is not same as this, the #238 is the CORS error  as the attached screenshot, and I found #249 is the same with me. So, can you guys give us some advice to resolve this problem, Thanks again~!

<img width="2890" height="1680" alt="Image" src="https://github.com/user-attachments/assets/7729d5c1-a0ec-4f77-bac7-c8470e33b8ee" />

**Comment by harrisonyao** [comment]
I checked the backend.log file and found the port number has been already been used, so I stop the process which used the 8000 port and restart valuecell, CORS error has been fixed, Thanks.

**Comment by Lingfeng713** [comment]
> > [[@Lingfeng713](https://github.com/Lingfeng713)]@(https://github.com/Lingfeng713)  Noticed that you are still facing this issue, as replied in [#238](https://github.com/ValueCell-ai/valuecell/issues/238) . This issue is reopened and could you please provide more details for us to better investigate?
> 
> @vcfgvThank you for your support. As per your previous guidance, I have git the latest code and also deleted valuecell.db before running the program again. Currently, I am able to use the Agent normally, but I still cannot retrieve stock data. I also tried using the Xueqiu token(xq_a_token), but it didn't work well . What other information do you think I need to provide?
> 
> <img alt="Image" width="482" height="419" src="https://private-user-images.githubusercontent.com/131430710/507454133-d26e2d49-7c40-45df-96d4-b6913ee4ee98.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE5MDEwNjIsIm5iZiI6MTc2MTkwMDc2MiwicGF0aCI6Ii8xMzE0MzA3MTAvNTA3NDU0MTMzLWQyNmUyZDQ5LTdjNDAtNDVkZi05NmQ0LWI2OTEzZWU0ZWU5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAzMVQwODUyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODhhNTcwZTYyMzVhMjBjM2U1MmE4YTljNzQ3NGNkZGUwMjUyODM4NzBiZGQzNjQ0ODkwYWVmMjY5YTRkMjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7cAa34kFtoP3X3MYrNiHkWmy1W-UuCLrPUgpOl7tesg"> <img alt="Image" width="1031" height="569" src="https://private-user-images.githubusercontent.com/131430710/507454136-d66e7a12-574e-497a-b264-552ddfbac9d7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE5MDEwNjIsIm5iZiI6MTc2MTkwMDc2MiwicGF0aCI6Ii8xMzE0MzA3MTAvNTA3NDU0MTM2LWQ2NmU3YTEyLTU3NGUtNDk3YS1iMjY0LTU1MmRkZmJhYzlkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAzMVQwODUyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWJmNDM1OGM4MGJiMjMxMmM4ZDUxZDc4MzQ4MTExZTM4ZDBiMTJhMmFiMWQwMWIxMTgzYTlkYjZhYzZhNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YevBD_3ok2XbAGel1pset431SXi_hb2tmM5BF9-KWuA"> <img alt="Image" width="826" height="96" src="https://private-user-images.githubusercontent.com/131430710/507454135-f7c26346-9389-4ab0-82e8-303fa344f4aa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE5MDEwNjIsIm5iZiI6MTc2MTkwMDc2MiwicGF0aCI6Ii8xMzE0MzA3MTAvNTA3NDU0MTM1LWY3YzI2MzQ2LTkzODktNGFiMC04MmU4LTMwM2ZhMzQ0ZjRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAzMVQwODUyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2JlNTE4N2IwZjVhMmUxMDkyNDZhZmM0NGUzODYxODI1MDQ3ODkzNjkwMWVjZTRkZTg5NWQwOGIzNDM4NzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VS41XbeJBa1V_2r_g6fPOz3tLMgKU-JeAcR3WqRwACA"> <img alt="Image" width="1080" height="588" src="https://private-user-images.githubusercontent.com/131430710/507454134-1e1a3e9e-52b0-4822-b083-53c2d8f7e0ba.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE5MDEwNjIsIm5iZiI6MTc2MTkwMDc2MiwicGF0aCI6Ii8xMzE0MzA3MTAvNTA3NDU0MTM0LTFlMWEzZTllLTUyYjAtNDgyMi1iMDgzLTUzYzJkOGY3ZTBiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAzMVQwODUyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTc3NzllYTUyMjMxMjU2ZmUxNmM1Y2FjN2YxOTY4MTYxOTZhZWM2ZjI2NThmYWZlNjJlODk2YzQ5ZDBmYjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PrBhMVk3pVlvOBcziitXe8oK-orIBGiegWXIL3fv0hM">

@vcfgv Additionally, I have provided more information. Is there any progress? Thx

![Image](https://github.com/user-attachments/assets/31ba8b7c-3297-4dc6-abb1-5b164b280507)

![Image](https://github.com/user-attachments/assets/bb5dead0-a753-4400-a1e2-c0e303584e25)

**Comment by vcfgv** [comment]
Thank you for the report. Unfortunately, we couldn't reproduce the issue. Our current guess is that it might be related to your network environment. We will continue to monitor this and provide updates if we find anything new.

**Comment by Lingfeng713** [comment]
> Thank you for the report. Unfortunately, we couldn't reproduce the issue. Our current guess is that it might be related to your network environment. We will continue to monitor this and provide updates if we find anything new.

@vcfgv Thx，I hope this issue can be resolved quickly, as many people are experiencing this error.

**Comment by Muzzz99** [comment]
The same error me too

**Comment by jiapumin** [comment]
The same error me too
